### ISSUE TITLE
Small mistake README

### ISSUE THREAD

**Issue by cdupont** [argussecurity/raspberry-pi-remote-flashing#4]
I'm trying to prepare the recovery image, but it seems that there is a small mistake in the readme file in this section:

https://github.com/argussecurity/raspberry-pi-remote-flashing/blob/master/recovery_image/README.md#preparing-u-boot

The readme does not instruct to clone this repo, so the patches are not available at this line:
```
# Apply Patches
cd u-boot-2019.10
for i in patches/u-boot/*.patch; do patch -p1 < $i; done
```

**Comment by itaysp** [comment]
You are right, thanks, I will update this
